const { createClient } = window.supabase;
let pdfjsLib = null;
const cfg = window.RUDRAKSH_CONFIG || {};
async function ensurePdfLib(){ if(!pdfjsLib) pdfjsLib = await import('https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.4.168/pdf.min.mjs'); return pdfjsLib; }
const app = document.getElementById('app');
const ready = cfg.SUPABASE_URL && cfg.SUPABASE_URL.startsWith('https://') && cfg.SUPABASE_ANON_KEY && !cfg.SUPABASE_ANON_KEY.includes('PASTE_');
let sb = null;
let session = null;
let currentUser = null;
let state = { tab:'dashboard', questions:[], students:[], tests:[], reports:[], attempt:null };
if (ready) sb = createClient(cfg.SUPABASE_URL, cfg.SUPABASE_ANON_KEY);

const esc = s => String(s ?? '').replace(/[&<>\"]/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
const fmt = s => s ? new Date(s).toLocaleString() : '—';
const page = (title, body, actions='') => `<div class="topbar"><div class="brand">RUDRAKSH CBT EXAMINATION</div><div>${actions}</div></div><main class="container"><div class="card"><h1 style="margin:0 0 4px">${title}</h1><div class="muted">Professional online CBT management system</div></div>${body}</main>`;
const nav = role => `<div class="tabs">${['dashboard','questions','import','tests','students','reports'].map(t=>`<button class="${state.tab===t?'active':''}" data-tab="${t}">${t[0].toUpperCase()+t.slice(1)}</button>`).join('')}</div>`;

async function boot(){
  if(!ready) return renderSetup();
  const {data:{session:s}} = await sb.auth.getSession(); session=s;
  if(!session) return renderLogin();
  const {data:u,error} = await sb.from('profiles').select('*').eq('id', session.user.id).single();
  if(error) return renderError('Your Supabase Auth user exists, but its profile row is missing. Follow the setup checklist to add the teacher/student profile.');
  currentUser=u; renderApp();
}
function renderSetup(){ app.innerHTML=page('Online setup required',`<section class="card" style="margin-top:18px"><div class="notice"><b>One-time setup:</b> open <code>public/config.js</code> and replace the two placeholders with your Supabase project URL and public anonymous key. Never paste the service-role key.</div><p>Then upload this folder to GitHub and deploy it with Cloudflare Pages.</p><pre style="white-space:pre-wrap;background:#101a2a;color:#dce8ff;padding:16px;border-radius:12px">SUPABASE_URL: 'https://YOURPROJECT.supabase.co'\nSUPABASE_ANON_KEY: 'YOUR_PUBLIC_ANON_KEY'</pre></section>`);}
function renderError(msg){ app.innerHTML=page('Setup issue',`<section class="card" style="margin-top:18px"><div class="notice">${esc(msg)}</div></section>`); }
function renderLogin(){ app.innerHTML=page('Secure Login',`<section class="login-wrap"><div class="card login-card"><h2>Sign in</h2><div class="muted">Teacher and Student access</div><div style="margin-top:16px"><label>Login ID<input id="loginId" placeholder="Teacher ID / Student ID"></label></div><div style="margin-top:12px"><label>Password<input id="loginPw" type="password" placeholder="Password"></label></div><div class="actions" style="margin-top:16px"><button id="loginBtn">Sign in</button></div><p id="loginMsg" class="muted"></p></div></section>`); document.getElementById('loginBtn').onclick=login; }
async function login(){ const id=document.getElementById('loginId').value.trim(); const pw=document.getElementById('loginPw').value; const msg=document.getElementById('loginMsg'); msg.textContent='Signing in…';
  // User-facing IDs are mapped to internal auth emails in the database via id_to_auth_email RPC.
  const {data:email,error} = await sb.rpc('id_to_auth_email',{p_login_id:id}); if(error||!email){msg.textContent='Invalid ID or setup not complete.';return;}
  const {data,error:e}=await sb.auth.signInWithPassword({email,password:pw}); if(e){msg.textContent=e.message;return;} session=data.session; const {data:u}=await sb.from('profiles').select('*').eq('id',session.user.id).single(); currentUser=u; state={tab:'dashboard',questions:[],students:[],tests:[],reports:[],attempt:null}; renderApp(); }
async function logout(){await sb.auth.signOut();session=null;currentUser=null;renderLogin();}

function renderApp(){ if(state.tab==='exam') return renderExam(); if(currentUser.role==='teacher') renderTeacher(); else renderStudent(); }
function bindNav(){document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;renderApp();}); document.querySelectorAll('#logout').forEach(b=>b.onclick=logout);}

async function renderTeacher(){
  const [q,t,st,r]=await Promise.all([sb.from('questions').select('*').order('created_at',{ascending:false}),sb.from('tests').select('id,title,duration_minutes,negative_mark,status,created_at'),sb.from('profiles').select('id,login_id,display_name,role').eq('role','student').order('display_name'),sb.from('attempts').select('id,test_id,student_id,score,correct_count,wrong_count,skipped_count,accuracy,submitted_at').not('submitted_at','is',null).order('submitted_at',{ascending:false})]);
  state.questions=q.data||[];state.tests=t.data||[];state.students=st.data||[];state.reports=r.data||[];
  const body=nav('teacher')+(state.tab==='dashboard'?teacherDashboard():state.tab==='questions'?teacherQuestions():state.tab==='import'?teacherImport():state.tab==='tests'?teacherTests():state.tab==='students'?teacherStudents():teacherReports());
  app.innerHTML=page(`Teacher Dashboard`,`<div class="muted">Welcome, ${esc(currentUser.display_name)} · ${esc(currentUser.login_id)}</div>${body}`,`<button id="logout" class="secondary">Logout</button>`);bindNav();attachTeacherActions();
}
function teacherDashboard(){return `<section class="grid stats" style="margin-top:18px"><div class="stat"><div>Questions</div><div class="num">${state.questions.length}</div></div><div class="stat"><div>Tests</div><div class="num">${state.tests.length}</div></div><div class="stat"><div>Students</div><div class="num">${state.students.length}</div></div><div class="stat"><div>Submitted Attempts</div><div class="num">${state.reports.length}</div></div></section><section class="card" style="margin-top:18px"><h2>Professional workflow</h2><p class="muted">1. Import questions → 2. Review answers → 3. Create test → 4. Assign students → 5. Monitor performance</p></section>`;}
function teacherQuestions(){return `<section class="card" style="margin-top:18px"><div class="actions"><button data-action="add">Add Question</button><button data-tab="import" class="secondary">Import File</button></div><div style="overflow:auto;margin-top:16px"><table><thead><tr><th>ID</th><th>Chapter</th><th>Topic</th><th>Source</th><th>Question</th><th>Answer</th></tr></thead><tbody>${state.questions.map(q=>`<tr><td>${esc(q.question_no||q.id)}</td><td>${esc(q.chapter)}</td><td>${esc(q.topic)}</td><td>${esc(q.source)}</td><td>${esc(q.question)}</td><td><span class="pill">Teacher only</span></td></tr>`).join('')||'<tr><td colspan="6" class="muted">No questions yet. Ma’am can import or add the first question.</td></tr>'}</tbody></table></div></section>`;}
function teacherImport(){return `<section class="card" style="margin-top:18px"><h2>Import Question Bank</h2><p class="muted">Supported source files: PDF, DOCX, XLSX, CSV, TXT. Supported answer files: same formats. The system previews before saving.</p><div class="form-grid"><div class="field"><label>Question file<input id="qFile" type="file" accept=".pdf,.docx,.xlsx,.xls,.csv,.txt"></label></div><div class="field"><label>Answer key file<input id="aFile" type="file" accept=".pdf,.docx,.xlsx,.xls,.csv,.txt"></label></div><div><label>Subject<input id="impSubject" placeholder="Biology"></label></div><div><label>Chapter<input id="impChapter" placeholder="Chapter name"></label></div></div><div class="actions" style="margin-top:14px"><button id="previewImport">Preview</button></div><div id="importPreview" style="margin-top:16px"></div></section>`;}
function teacherTests(){return `<section class="card" style="margin-top:18px"><h2>Create Test</h2><div class="form-grid"><div><label>Test title<input id="testTitle" placeholder="Biology Test 01"></label></div><div><label>Duration (minutes)<input id="testDur" type="number" value="180"></label></div><div><label>Negative marking per wrong answer<input id="testNeg" type="number" step="0.01" value="0"></label></div><div><label>Assign students<select id="testStudents" multiple size="4">${state.students.map(s=>`<option value="${s.id}">${esc(s.display_name)} (${esc(s.login_id)})</option>`).join('')}</select></label></div></div><h3 style="margin-top:20px">Select Questions</h3><div style="max-height:360px;overflow:auto;border:1px solid var(--border);border-radius:12px;padding:8px">${state.questions.map((q,i)=>`<label style="display:flex;gap:10px;padding:8px;border-bottom:1px solid var(--border)"><input class="qPick" type="checkbox" value="${q.id}"> <span><b>${i+1}.</b> ${esc(q.question)}</span></label>`).join('')||'<p class="muted">No questions available yet.</p>'}</div><div class="actions" style="margin-top:14px"><button id="createTest">Create & Assign Test</button></div><p id="testMsg" class="muted"></p></section><section class="card" style="margin-top:18px"><h2>Existing Tests</h2><table><thead><tr><th>Title</th><th>Duration</th><th>Questions</th><th>Status</th></tr></thead><tbody>${state.tests.map(t=>`<tr><td>${esc(t.title)}</td><td>${t.duration_minutes} min</td><td>Stored in test_questions</td><td><span class="pill">${esc(t.status)}</span></td></tr>`).join('')||'<tr><td colspan="4" class="muted">No tests yet.</td></tr>'}</tbody></table></section>`;}
function teacherStudents(){return `<section class="card" style="margin-top:18px"><h2>Students</h2><table><thead><tr><th>Student ID</th><th>Name</th><th>Role</th></tr></thead><tbody>${state.students.map(s=>`<tr><td>${esc(s.login_id)}</td><td>${esc(s.display_name)}</td><td>Student</td></tr>`).join('')||'<tr><td colspan="3" class="muted">No students yet.</td></tr>'}</tbody></table><p class="muted" style="margin-top:12px">Student account provisioning is intentionally separated from public pages; later we can add a teacher-only “Create Student” flow backed by a secure server function.</p></section>`;}
function teacherReports(){return `<section class="card" style="margin-top:18px"><h2>Performance Reports</h2><table><thead><tr><th>Student</th><th>Test</th><th>Score</th><th>Correct</th><th>Wrong</th><th>Skipped</th><th>Accuracy</th><th>Date</th></tr></thead><tbody>${state.reports.map(r=>`<tr><td>${esc(r.student_id)}</td><td>${esc(r.test_id)}</td><td>${r.score}</td><td>${r.correct_count}</td><td>${r.wrong_count}</td><td>${r.skipped_count}</td><td>${Number(r.accuracy||0).toFixed(1)}%</td><td>${fmt(r.submitted_at)}</td></tr>`).join('')||'<tr><td colspan="8" class="muted">No submitted attempts yet.</td></tr>'}</tbody></table></section>`;}

function attachTeacherActions(){ const add=document.querySelector('[data-action="add"]');if(add)add.onclick=()=>{app.innerHTML=page('Add Question',`<section class="card" style="margin-top:18px"><div class="form-grid"><div><label>Subject<input id="mSubject"></label></div><div><label>Chapter<input id="mChapter"></label></div><div><label>Topic<input id="mTopic"></label></div><div><label>Source<input id="mSource" value="Teacher Added"></label></div><div><label>Question No.<input id="mNo"></label></div><div class="field full"><label>Question<textarea id="mQuestion"></textarea></label></div>${[1,2,3,4].map(i=>`<div><label>Option ${i}<input id="mO${i}"></label></div>`).join('')}<div><label>Correct answer (teacher-only)<select id="mAns"><option value="0">Option 1</option><option value="1">Option 2</option><option value="2">Option 3</option><option value="3">Option 4</option></select></label></div><div class="field full"><label>Teacher-only explanation<textarea id="mExp"></textarea></label></div></div><div class="actions" style="margin-top:14px"><button id="saveManual">Save Question</button><button class="secondary" data-back="questions">Cancel</button></div><p id="manualMsg" class="muted"></p></section>`,`<button id="logout" class="secondary">Logout</button>`);document.getElementById('saveManual').onclick=saveManual;document.querySelector('[data-back]')?.addEventListener('click',()=>{state.tab='questions';renderApp();});document.getElementById('logout').onclick=logout;};
  const p=document.getElementById('previewImport'); if(p)p.onclick=previewImport;
  const ct=document.getElementById('createTest'); if(ct)ct.onclick=createTest;
}
async function saveManual(){const b={subject:val('mSubject'),chapter:val('mChapter'),topic:val('mTopic'),source:val('mSource'),question_no:val('mNo'),question:val('mQuestion'),options:[1,2,3,4].map(i=>val('mO'+i)),correct_index:Number(val('mAns')),explanation:val('mExp')}; const {error}=await sb.from('questions').insert(b);document.getElementById('manualMsg').textContent=error?error.message:'Question saved successfully.';if(!error){state.tab='questions';setTimeout(renderApp,400);}}
const val=id=>document.getElementById(id)?.value||'';
async function createTest(){const ids=[...document.querySelectorAll('.qPick:checked')].map(x=>x.value);const students=[...document.getElementById('testStudents').selectedOptions].map(o=>o.value);const msg=document.getElementById('testMsg');if(!ids.length){msg.textContent='Select at least one question.';return} if(!students.length){msg.textContent='Select at least one student.';return}
  const {data:t,error}=await sb.from('tests').insert({title:val('testTitle')||'Untitled Test',duration_minutes:Number(val('testDur')||180),negative_mark:Number(val('testNeg')||0),teacher_id:currentUser.id,status:'published'}).select().single();if(error){msg.textContent=error.message;return}
  await sb.from('test_questions').insert(ids.map((q,i)=>({test_id:t.id,question_id:q,position:i+1})));await sb.from('test_assignments').insert(students.map(s=>({test_id:t.id,student_id:s})));msg.textContent='Test created and assigned successfully.';}

function renderStudent(){ const body=`<section class="grid stats" style="margin-top:18px"><div class="stat"><div>Tests Attempted</div><div class="num" id="sAttempted">—</div></div><div class="stat"><div>Correct</div><div class="num" id="sCorrect">—</div></div><div class="stat"><div>Wrong</div><div class="num" id="sWrong">—</div></div><div class="stat"><div>Accuracy</div><div class="num" id="sAcc">—</div></div></section><section class="card" style="margin-top:18px"><h2>Available Tests</h2><div id="studentTests">Loading…</div></section><section class="card" style="margin-top:18px"><h2>My Past Reports</h2><div id="studentReports">Loading…</div></section>`;app.innerHTML=page(`Student Dashboard`,`<div class="muted">Welcome, ${esc(currentUser.display_name)} · ${esc(currentUser.login_id)}</div>${body}`,`<button id="logout" class="secondary">Logout</button>`);document.getElementById('logout').onclick=logout;loadStudentData();}
async function loadStudentData(){
 const {data:assigns}=await sb.from('test_assignments').select('test_id,assigned_at,tests(id,title,duration_minutes,negative_mark,status)').eq('student_id',currentUser.id).eq('tests.status','published').order('assigned_at',{ascending:false});
 document.getElementById('studentTests').innerHTML=(assigns||[]).map(a=>`<div class="metric" style="margin:8px 0"><b>${esc(a.tests.title)}</b><div class="muted">${a.tests.duration_minutes} min · Negative ${a.tests.negative_mark}</div><div class="actions" style="margin-top:8px"><button data-start="${a.test_id}">Start Test</button></div></div>`).join('')||'<p class="muted">No tests assigned yet.</p>';
 document.querySelectorAll('[data-start]').forEach(b=>b.onclick=()=>startTest(b.dataset.start));
 const {data:r}=await sb.from('attempts').select('id,test_id,score,correct_count,wrong_count,skipped_count,accuracy,submitted_at,tests(title)').eq('student_id',currentUser.id).not('submitted_at','is',null).order('submitted_at',{ascending:false});
 let c=0,w=0,n=0; (r||[]).forEach(x=>{c+=x.correct_count||0;w+=x.wrong_count||0;n++;});document.getElementById('sAttempted').textContent=n;document.getElementById('sCorrect').textContent=c;document.getElementById('sWrong').textContent=w;document.getElementById('sAcc').textContent=((c/Math.max(1,c+w))*100).toFixed(1)+'%';
 document.getElementById('studentReports').innerHTML=(r||[]).map(x=>`<div class="metric" style="margin:8px 0"><b>${esc(x.tests.title)}</b><div class="muted">${fmt(x.submitted_at)}</div><div class="report-grid"><div>Score<strong>${x.score}</strong></div><div>Correct<strong>${x.correct_count}</strong></div><div>Wrong<strong>${x.wrong_count}</strong></div></div><p>Accuracy: <b>${Number(x.accuracy||0).toFixed(1)}%</b> · Skipped: <b>${x.skipped_count}</b></p><button class="secondary" data-report="${x.id}">Detailed report</button></div>`).join('')||'<p class="muted">No completed tests yet.</p>'; document.querySelectorAll('[data-report]').forEach(b=>b.onclick=()=>studentReport(b.dataset.report)); }
async function studentReport(id){const {data:r,error}=await sb.from('attempt_reports').select('*').eq('attempt_id',id).order('position');if(error){alert(error.message);return} app.innerHTML=page('Detailed Test Report',`<section class="card" style="margin-top:18px"><table><thead><tr><th>Q.</th><th>Question</th><th>Your Answer</th><th>Result</th></tr></thead><tbody>${(r||[]).map((x,i)=>`<tr><td>${i+1}</td><td>${esc(x.question)}</td><td>${esc(x.selected_option||'Skipped')}</td><td><span class="pill ${x.state==='correct'?'good':'bad'}">${esc(x.state)}</span></td></tr>`).join('')}</tbody></table></section>`,`<button id="logout" class="secondary">Logout</button>`);document.getElementById('logout').onclick=logout;}

async function startTest(testId){const {data:a,error}=await sb.from('attempts').insert({test_id:testId,student_id:currentUser.id}).select().single();if(error){alert(error.message);return}const {data:qs,error:e}=await sb.rpc('get_student_test_questions',{p_test_id:testId});if(e){alert(e.message);return}state.attempt={attempt:a,questions:qs||[],index:0,answers:{},marked:new Set(),deadline:Date.now()+(((await sb.from('tests').select('duration_minutes').eq('id',testId).single()).data?.duration_minutes||180)*60000)};state.tab='exam';renderExam();}
function renderExam(){const a=state.attempt;if(!a){state.tab='dashboard';return renderApp()}const q=a.questions[a.index];app.innerHTML=`<div class="topbar"><div class="brand">RUDRAKSH CBT EXAMINATION</div><div><span class="pill" style="margin-right:10px;background:#fff;color:var(--navy)" id="timer"></span><button id="submitExam" class="danger">Submit Test</button></div></div><main class="container"><div class="exam-layout"><section class="card"><div class="muted">Question ${a.index+1} of ${a.questions.length}</div><div class="question-text" style="margin-top:14px">${esc(q.question)}</div><div style="margin-top:18px">${q.options.map((o,i)=>`<label class="option ${a.answers[q.id]===i?'selected':''}"><input type="radio" name="opt" value="${i}" ${a.answers[q.id]===i?'checked':''}> <span><b>${String.fromCharCode(65+i)}.</b> ${esc(o)}</span></label>`).join('')}</div><div class="actions" style="margin-top:20px"><button class="secondary" id="prev">Previous</button><button class="secondary" id="clear">Clear</button><button class="secondary" id="mark">${a.marked.has(q.id)?'Unmark Review':'Mark for Review'}</button><button id="next">${a.index===a.questions.length-1?'Finish':'Save & Next'}</button></div></section><aside class="card"><h3>Question Palette</h3><div class="palette">${a.questions.map((x,i)=>`<button class="qnum ${a.answers[x.id]!==undefined?'answered':''} ${a.marked.has(x.id)?'review':''} ${i===a.index?'current':''}" data-i="${i}">${i+1}</button>`).join('')}</div><div style="margin-top:16px"><span class="pill good">Answered</span> <span class="pill">Not Answered</span> <span class="pill review">Review</span></div></aside></div></main>`;document.querySelectorAll('[name="opt"]').forEach(r=>r.onchange=()=>{a.answers[q.id]=Number(r.value);renderExam();});document.getElementById('prev').onclick=()=>{if(a.index>0){a.index--;renderExam()}};document.getElementById('next').onclick=()=>{if(a.index<a.questions.length-1){a.index++;renderExam()}else submitExam()};document.getElementById('clear').onclick=()=>{delete a.answers[q.id];renderExam()};document.getElementById('mark').onclick=()=>{a.marked.has(q.id)?a.marked.delete(q.id):a.marked.add(q.id);renderExam()};document.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>{a.index=Number(b.dataset.i);renderExam()});document.getElementById('submitExam').onclick=submitExam;tick();}
let timerHandle=null;function tick(){clearInterval(timerHandle);timerHandle=setInterval(()=>{const left=Math.max(0,state.attempt.deadline-Date.now());const m=Math.floor(left/60000),s=Math.floor(left/1000)%60;const el=document.getElementById('timer');if(el)el.textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;if(left<=0){clearInterval(timerHandle);submitExam();}},1000);}
async function submitExam(){clearInterval(timerHandle);const a=state.attempt;const {data,error}=await sb.from('attempt_answers').upsert(Object.entries(a.answers).map(([question_id,selected_index])=>({attempt_id:a.attempt.id,question_id,selected_index})),{onConflict:'attempt_id,question_id'});if(error){alert(error.message);return}const {error:e}=await sb.rpc('submit_attempt',{p_attempt_id:a.attempt.id});if(e){alert(e.message);return}state.attempt=null;state.tab='dashboard';renderApp();}
async function previewImport(){const qf=document.getElementById('qFile').files[0],af=document.getElementById('aFile').files[0], box=document.getElementById('importPreview');if(!qf){box.innerHTML='<div class="notice">Choose a question file first.</div>';return}box.innerHTML='<div class="muted">Reading files…</div>';try{const qt=await readFile(qf), at=af?await readFile(af):'';const parsed=parseSimpleQuestions(qt,at);box.innerHTML=`<div class="notice">Preview: ${parsed.length} structured question(s) detected. Please review the preview before importing.</div><div style="overflow:auto;max-height:430px"><table><thead><tr><th>#</th><th>Question</th><th>Options</th><th>Answer</th></tr></thead><tbody>${parsed.slice(0,80).map((p,i)=>`<tr><td>${i+1}</td><td>${esc(p.question)}</td><td>${p.options.map((o,j)=>String.fromCharCode(65+j)+'. '+esc(o)).join('<br>')}</td><td>${p.answer==null?'Unmapped':'Option '+(p.answer+1)}</td></tr>`).join('')}</tbody></table></div><div class="actions" style="margin-top:12px"><button id="importNow" ${parsed.length?'':'disabled'}>Import Previewed Questions</button></div>`;document.getElementById('importNow').onclick=async()=>{const rows=parsed.map(p=>({subject:val('impSubject'),chapter:val('impChapter')||'Imported',topic:p.topic||'',source:qf.name,question_no:p.number,question:p.question,options:p.options,correct_index:p.answer,explanation:p.explanation||''}));const valid=rows.filter(x=>x.correct_index!==null); if(valid.length<rows.length&&!confirm(`${rows.length-valid.length} question(s) have no mapped answer. Import anyway as teacher-review pending?`))return;const {error}=await sb.from('questions').insert(rows);box.innerHTML=error?`<div class="notice">${esc(error.message)}</div>`:`<div class="notice">Imported ${rows.length} question(s). Answer mappings still require teacher review where blank.</div>`;};}catch(e){box.innerHTML=`<div class="notice">${esc(e.message)}</div>`;}}
async function readFile(f){const ext=f.name.toLowerCase().split('.').pop();if(ext==='txt'||ext==='csv')return await f.text();if(ext==='docx'){const a=await f.arrayBuffer();return (await window.mammoth.extractRawText({arrayBuffer:a})).value;}if(ext==='xlsx'||ext==='xls'){const a=await f.arrayBuffer();const wb=XLSX.read(a,{type:'array'});return wb.SheetNames.map(n=>XLSX.utils.sheet_to_csv(wb.Sheets[n])).join('\n');}if(ext==='pdf'){const lib=await ensurePdfLib();const pdf=await lib.getDocument({data:new Uint8Array(await f.arrayBuffer())}).promise;let out='';for(let i=1;i<=pdf.numPages;i++){const p=await pdf.getPage(i);const tc=await p.getTextContent();out+=tc.items.map(x=>x.str).join(' ')+'\n';}return out;}throw new Error('Unsupported file type');}
function parseSimpleQuestions(text,answerText=''){const lines=text.replace(/\r/g,'').split(/\n/).map(x=>x.trim()).filter(Boolean), out=[];let i=0;const ansMap={};for(const m of answerText.matchAll(/(?:Que\.?|Q\.?|Question)\s*(\d+)\s*[:.-]?\s*([1-4A-D])/gi))ansMap[Number(m[1])]=String(m[2]).toUpperCase();for(;i<lines.length;i++){const m=lines[i].match(/^(\d+)\.\s+(.+)/);if(!m)continue;let q=m[2],n=Number(m[1]);i++;const opts=[];while(i<lines.length&&opts.length<4){const om=lines[i].match(/^\((\d)\)\s+(.+)/);if(om){opts[Number(om[1])-1]=om[2];i++;}else if(/^\d+\.\s+/.test(lines[i]))break;else {q+=' '+lines[i];i++;}}if(opts.length===4&&opts.every(Boolean)){const av=ansMap[n];let ai=av?(['1','2','3','4','A','B','C','D'].indexOf(av)): -1;if(ai>=4)ai-=4;out.push({number:n,question:q,options:opts,answer:ai>=0?ai:null});} }return out;}

boot();
